name: SB-lab CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [dev-front]
  pull_request:
    branches: [dev-front]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: eslint...
        run: npm run eslint
      - name: stylelint...
        run: npm run stylelint
      - name: unit test
        run: npm run unit
      - name: build storybook...
        run: npm run sb:build
